/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminShellUsersRouteImport } from './routes/admin/_shell/users'
import { Route as AdminShellDashboardRouteImport } from './routes/admin/_shell/dashboard'
import { Route as AdminShellAuditLogsRouteImport } from './routes/admin/_shell/audit-logs'
import { Route as AdminShellActivateHospitalRouteImport } from './routes/admin/_shell/activate-hospital'
import { Route as AdminShellPackagesIndexRouteImport } from './routes/admin/_shell/packages/index'
import { Route as AdminShellHospitalsIndexRouteImport } from './routes/admin/_shell/hospitals/index'
import { Route as AdminShellPackagesCreateRouteImport } from './routes/admin/_shell/packages/create'
import { Route as AdminShellHospitalsCreateRouteImport } from './routes/admin/_shell/hospitals/create'
import { Route as AdminShellHospitalsIdRouteImport } from './routes/admin/_shell/hospitals/$id'
import { Route as AdminShellCatalogModulesRouteImport } from './routes/admin/_shell/catalog/modules'
import { Route as AdminShellCatalogFeaturesRouteImport } from './routes/admin/_shell/catalog/features'
import { Route as AdminShellPackagesIdEditRouteImport } from './routes/admin/_shell/packages/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellUsersRoute = AdminShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellDashboardRoute = AdminShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAuditLogsRoute = AdminShellAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellActivateHospitalRoute =
  AdminShellActivateHospitalRouteImport.update({
    id: '/activate-hospital',
    path: '/activate-hospital',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellPackagesIndexRoute = AdminShellPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellHospitalsIndexRoute =
  AdminShellHospitalsIndexRouteImport.update({
    id: '/hospitals/',
    path: '/hospitals/',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellPackagesCreateRoute =
  AdminShellPackagesCreateRouteImport.update({
    id: '/packages/create',
    path: '/packages/create',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellHospitalsCreateRoute =
  AdminShellHospitalsCreateRouteImport.update({
    id: '/hospitals/create',
    path: '/hospitals/create',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellHospitalsIdRoute = AdminShellHospitalsIdRouteImport.update({
  id: '/hospitals/$id',
  path: '/hospitals/$id',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCatalogModulesRoute =
  AdminShellCatalogModulesRouteImport.update({
    id: '/catalog/modules',
    path: '/catalog/modules',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellCatalogFeaturesRoute =
  AdminShellCatalogFeaturesRouteImport.update({
    id: '/catalog/features',
    path: '/catalog/features',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellPackagesIdEditRoute =
  AdminShellPackagesIdEditRouteImport.update({
    id: '/packages/$id/edit',
    path: '/packages/$id/edit',
    getParentRoute: () => AdminShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/activate-hospital': typeof AdminShellActivateHospitalRoute
  '/admin/audit-logs': typeof AdminShellAuditLogsRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/users': typeof AdminShellUsersRoute
  '/admin/catalog/features': typeof AdminShellCatalogFeaturesRoute
  '/admin/catalog/modules': typeof AdminShellCatalogModulesRoute
  '/admin/hospitals/$id': typeof AdminShellHospitalsIdRoute
  '/admin/hospitals/create': typeof AdminShellHospitalsCreateRoute
  '/admin/packages/create': typeof AdminShellPackagesCreateRoute
  '/admin/hospitals/': typeof AdminShellHospitalsIndexRoute
  '/admin/packages/': typeof AdminShellPackagesIndexRoute
  '/admin/packages/$id/edit': typeof AdminShellPackagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/activate-hospital': typeof AdminShellActivateHospitalRoute
  '/admin/audit-logs': typeof AdminShellAuditLogsRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/users': typeof AdminShellUsersRoute
  '/admin/catalog/features': typeof AdminShellCatalogFeaturesRoute
  '/admin/catalog/modules': typeof AdminShellCatalogModulesRoute
  '/admin/hospitals/$id': typeof AdminShellHospitalsIdRoute
  '/admin/hospitals/create': typeof AdminShellHospitalsCreateRoute
  '/admin/packages/create': typeof AdminShellPackagesCreateRoute
  '/admin/hospitals': typeof AdminShellHospitalsIndexRoute
  '/admin/packages': typeof AdminShellPackagesIndexRoute
  '/admin/packages/$id/edit': typeof AdminShellPackagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_shell/activate-hospital': typeof AdminShellActivateHospitalRoute
  '/admin/_shell/audit-logs': typeof AdminShellAuditLogsRoute
  '/admin/_shell/dashboard': typeof AdminShellDashboardRoute
  '/admin/_shell/users': typeof AdminShellUsersRoute
  '/admin/_shell/catalog/features': typeof AdminShellCatalogFeaturesRoute
  '/admin/_shell/catalog/modules': typeof AdminShellCatalogModulesRoute
  '/admin/_shell/hospitals/$id': typeof AdminShellHospitalsIdRoute
  '/admin/_shell/hospitals/create': typeof AdminShellHospitalsCreateRoute
  '/admin/_shell/packages/create': typeof AdminShellPackagesCreateRoute
  '/admin/_shell/hospitals/': typeof AdminShellHospitalsIndexRoute
  '/admin/_shell/packages/': typeof AdminShellPackagesIndexRoute
  '/admin/_shell/packages/$id/edit': typeof AdminShellPackagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/activate-hospital'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/catalog/features'
    | '/admin/catalog/modules'
    | '/admin/hospitals/$id'
    | '/admin/hospitals/create'
    | '/admin/packages/create'
    | '/admin/hospitals/'
    | '/admin/packages/'
    | '/admin/packages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/activate-hospital'
    | '/admin/audit-logs'
    | '/admin/dashboard'
    | '/admin/users'
    | '/admin/catalog/features'
    | '/admin/catalog/modules'
    | '/admin/hospitals/$id'
    | '/admin/hospitals/create'
    | '/admin/packages/create'
    | '/admin/hospitals'
    | '/admin/packages'
    | '/admin/packages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/_shell'
    | '/admin/login'
    | '/admin/_shell/activate-hospital'
    | '/admin/_shell/audit-logs'
    | '/admin/_shell/dashboard'
    | '/admin/_shell/users'
    | '/admin/_shell/catalog/features'
    | '/admin/_shell/catalog/modules'
    | '/admin/_shell/hospitals/$id'
    | '/admin/_shell/hospitals/create'
    | '/admin/_shell/packages/create'
    | '/admin/_shell/hospitals/'
    | '/admin/_shell/packages/'
    | '/admin/_shell/packages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/users': {
      id: '/admin/_shell/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminShellUsersRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/dashboard': {
      id: '/admin/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminShellDashboardRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/audit-logs': {
      id: '/admin/_shell/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminShellAuditLogsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/activate-hospital': {
      id: '/admin/_shell/activate-hospital'
      path: '/activate-hospital'
      fullPath: '/admin/activate-hospital'
      preLoaderRoute: typeof AdminShellActivateHospitalRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/packages/': {
      id: '/admin/_shell/packages/'
      path: '/packages'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AdminShellPackagesIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/hospitals/': {
      id: '/admin/_shell/hospitals/'
      path: '/hospitals'
      fullPath: '/admin/hospitals/'
      preLoaderRoute: typeof AdminShellHospitalsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/packages/create': {
      id: '/admin/_shell/packages/create'
      path: '/packages/create'
      fullPath: '/admin/packages/create'
      preLoaderRoute: typeof AdminShellPackagesCreateRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/hospitals/create': {
      id: '/admin/_shell/hospitals/create'
      path: '/hospitals/create'
      fullPath: '/admin/hospitals/create'
      preLoaderRoute: typeof AdminShellHospitalsCreateRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/hospitals/$id': {
      id: '/admin/_shell/hospitals/$id'
      path: '/hospitals/$id'
      fullPath: '/admin/hospitals/$id'
      preLoaderRoute: typeof AdminShellHospitalsIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/catalog/modules': {
      id: '/admin/_shell/catalog/modules'
      path: '/catalog/modules'
      fullPath: '/admin/catalog/modules'
      preLoaderRoute: typeof AdminShellCatalogModulesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/catalog/features': {
      id: '/admin/_shell/catalog/features'
      path: '/catalog/features'
      fullPath: '/admin/catalog/features'
      preLoaderRoute: typeof AdminShellCatalogFeaturesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/packages/$id/edit': {
      id: '/admin/_shell/packages/$id/edit'
      path: '/packages/$id/edit'
      fullPath: '/admin/packages/$id/edit'
      preLoaderRoute: typeof AdminShellPackagesIdEditRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellActivateHospitalRoute: typeof AdminShellActivateHospitalRoute
  AdminShellAuditLogsRoute: typeof AdminShellAuditLogsRoute
  AdminShellDashboardRoute: typeof AdminShellDashboardRoute
  AdminShellUsersRoute: typeof AdminShellUsersRoute
  AdminShellCatalogFeaturesRoute: typeof AdminShellCatalogFeaturesRoute
  AdminShellCatalogModulesRoute: typeof AdminShellCatalogModulesRoute
  AdminShellHospitalsIdRoute: typeof AdminShellHospitalsIdRoute
  AdminShellHospitalsCreateRoute: typeof AdminShellHospitalsCreateRoute
  AdminShellPackagesCreateRoute: typeof AdminShellPackagesCreateRoute
  AdminShellHospitalsIndexRoute: typeof AdminShellHospitalsIndexRoute
  AdminShellPackagesIndexRoute: typeof AdminShellPackagesIndexRoute
  AdminShellPackagesIdEditRoute: typeof AdminShellPackagesIdEditRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellActivateHospitalRoute: AdminShellActivateHospitalRoute,
  AdminShellAuditLogsRoute: AdminShellAuditLogsRoute,
  AdminShellDashboardRoute: AdminShellDashboardRoute,
  AdminShellUsersRoute: AdminShellUsersRoute,
  AdminShellCatalogFeaturesRoute: AdminShellCatalogFeaturesRoute,
  AdminShellCatalogModulesRoute: AdminShellCatalogModulesRoute,
  AdminShellHospitalsIdRoute: AdminShellHospitalsIdRoute,
  AdminShellHospitalsCreateRoute: AdminShellHospitalsCreateRoute,
  AdminShellPackagesCreateRoute: AdminShellPackagesCreateRoute,
  AdminShellHospitalsIndexRoute: AdminShellHospitalsIndexRoute,
  AdminShellPackagesIndexRoute: AdminShellPackagesIndexRoute,
  AdminShellPackagesIdEditRoute: AdminShellPackagesIdEditRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
